server:
  port: 8081
spring:
  #*********************************************** Mysql start**********************************************************
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zch_data?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    #url: jdbc:mysql://localhost:3306/zch_data?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: "102030"
    initialSize: 20
    minIdle: 50
    maxActive: 500